export const endpoints = {
  login: '/auth/login',
  register: '/auth/register',
  me: '/auth/me',
  utenteMe: '/utente/me',
  utentes: '/utente',
  utenteSearch: (nome: string) => `/utente/search/${encodeURIComponent(nome)}`,
  utente: (id: number | string) => `/utente/${id}`,
  consultas: '/consultas',
  consultasMinhas: '/consultas/minhas',
  consulta: (id: number | string) => `/consultas/${id}`,
  consultaVideo: (id: number | string) => `/consultas/${id}/video`,
  medicacoes: (utenteId: number | string) => `/utentes/${utenteId}/medicacoes`,
  medicacao: (id: number | string) => `/medicacoes/${id}`,
  registos: (utenteId: number | string) => `/utentes/${utenteId}/registos`,
  registo: (id: number | string) => `/registos/${id}`,
  chatHistory: (room: string) => `/mensagens/history/${encodeURIComponent(room)}`,
} as const;
